spring.application.name=order-service
server.port=8082
spring.cloud.openfeign.circuitbreaker.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
resilience4j.circuitbreaker.instances.bookService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bookService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.bookService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bookService.waitDurationInOpenState=10s
